"""Capture-derived PictoChat application protocol codecs.

This package only handles PictoChat application records and transfer chunks.
It deliberately does not implement Nintendo local-multiplayer 802.11 framing,
association, polling, or timing.
"""

from .codec import (
    BACKING_WIDTH,
    CAPTURED_DRAWING_METADATA,
    DRAWING_HEADER_SIZE,
    IMAGE_BYTES_PER_ROW,
    MAX_IMAGE_ROWS,
    PROFILE_SIZE,
    VISIBLE_HEIGHT,
    VISIBLE_WIDTH,
    CodecError,
    DrawingRecord,
    ProfileRecord,
    TransferAnnouncement,
    TransferFragment,
    TransferReassembler,
    backing_to_visible,
    build_transfer,
    decode_profile,
    decode_tiled_image,
    decode_visible_image,
    encode_profile,
    encode_tiled_image,
    encode_visible_image,
    fragment_payload,
    pair_swap_mac,
    reassemble_transfer,
    visible_to_backing,
)

__all__ = [
    "BACKING_WIDTH",
    "CAPTURED_DRAWING_METADATA",
    "DRAWING_HEADER_SIZE",
    "IMAGE_BYTES_PER_ROW",
    "MAX_IMAGE_ROWS",
    "PROFILE_SIZE",
    "VISIBLE_HEIGHT",
    "VISIBLE_WIDTH",
    "CodecError",
    "DrawingRecord",
    "ProfileRecord",
    "TransferAnnouncement",
    "TransferFragment",
    "TransferReassembler",
    "backing_to_visible",
    "build_transfer",
    "decode_profile",
    "decode_tiled_image",
    "decode_visible_image",
    "encode_profile",
    "encode_tiled_image",
    "encode_visible_image",
    "fragment_payload",
    "pair_swap_mac",
    "reassemble_transfer",
    "visible_to_backing",
]
